pipeline {
    agent { label 'Nodejs' }
    environment {
        project = 'expense'
        component = 'backend'
        deploy_to = "production"

    }
    options {
        disableConcurrentBuilds()
        timeout(time : 30, unit : 'MINUTES')
        ansiColor('xterm')

    }
    stages {
        stage ('Init'){
            steps {
                script{
                    WithAWS(region: 'us-east-1' , credentials: 'aws-creds') {
                        sh """
                        cd 00-vpc
                        terraform init -reconfigure
                        """
                    }
                }
            }
        }

    }
    post {
        always {
            echo 'I will always say hello!'
            deleteDir()
        }
        failure {
            echo 'I will run when pipeline is failed!'
        }
        success {
            echo 'I will run pipeline is success'
        }
    }

}